QuizApp-main/QuizApp/Models/Answer.cs
namespace QuizApp.Models
{
    public class Answer
    {
        public Answer()
        {
            IsCorrect = false;
        }
        public int Id { get; set; }
        public string? AnswerText { get; set; }
        public bool? IsCorrect { get; set; }
        public int QuestionId { get; set; }
        public List<Input> Inputs { get; set; }
    }
}
 

QuizApp-main/QuizApp/Models/ErrorViewModel.cs
namespace QuizApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QuizApp-main/QuizApp/Models/Input.cs
namespace QuizApp.Models
{
    public class Input
    {
        public Input()
        {
            
        }
        public int ID { get; set; }
        public int RoundId { get; set; }
        public int AnswerId { get; set; }
        public bool IsCorrect { get; set; }
    }
}

QuizApp-main/QuizApp/Models/Player.cs
namespace QuizApp.Models
{
    public class Player
    {
        public Player(string name)
        {
            Name = name;
            HighestScore = 0;
            Wins = 0;
            Rounds = new List<Round>();

        }
        public int ID { get; set; }
        public string Name { get; set; }
        public int HighestScore { get; set; }

        public int Wins { get; set; }
        public List<Round> Rounds { get; set;}
    }
}

QuizApp-main/QuizApp/Models/Question.cs
namespace QuizApp.Models
{
    public class Question
    {
        public Question()
        {
            Answers = new List<Answer>();
        }
        public int Id { get; set; }
        public string? QuestionText { get; set; }
        public List<Answer> Answers { get; set; }
    }
}
 

QuizApp-main/QuizApp/Models/Round.cs
namespace QuizApp.Models
{
    public class Round
    {
        public int ID { get; set; }
        public int PlayerId { get; set; }
        public bool IsWon {  get; set; }

        public List<Input> Inputs { get; set; }
    }

}

QuizApp-main/QuizApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QuizApp.Models;
using System.Diagnostics;

namespace QuizApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QuizApp-main/QuizApp/Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Mvc;
using QuizApp.Models;
using QuizApp.Repositories;

namespace QuizApp.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly IQuestionsRepository _questionRepository;
        public QuestionsController(IQuestionsRepository questionRepository)
        {
            _questionRepository = questionRepository;
        }
        [HttpGet]
        public IActionResult GetQuestions()
        {
            var questions = _questionRepository.GetAllQuestions();
            return View("QuestionsList", questions);
        }

        [HttpGet]
        public IActionResult AddQuestion()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddQuestion(Question question)
        {
            _questionRepository.AddQuestion(question);
            return RedirectToAction("AddQuestion");
        }

        [HttpPost]
        public IActionResult DeleteQuestion(int id)
        {
            _questionRepository.DeleteQuestion(id);
            return RedirectToAction("GetQuestions");
        }
    }
}

QuizApp-main/QuizApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-5">
    <h2>Welcome!</h2>
</div>

QuizApp-main/QuizApp/Views/Questions/AddQuestion.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Question";
}
<div class="container">
    <div class="col-md-15">
        <div class="question-container">
            <h2 class="mb-4">Add Question</h2>
            <form asp-controller="Questions" asp-action="AddQuestion" method="post">
                <div class="form-group">
                    <label for="questionText">Question:</label>
                    <input type="text" id="questionText" name="QuestionText" class="form-control mb-3" />
                </div>
                <h3 class="mb-3">Answers</h3>
                @for (var i = 0; i < 4; i++)
                {
                    <div class="form-check">
                        <input type="radio" name="Answers[@i].IsCorrect" class="form-check-input" value="true"/>
                        <input type="text" name="Answers[@i].AnswerText" class="form-control mb-2" placeholder="Answer @i" />
                    </div>
                }
                <button type="submit" class="btn btn-primary">Add Question</button>
            </form>
        </div>
    </div>
</div>

QuizApp-main/QuizApp/Views/Questions/QuestionsList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Questions List";
}
@model List<Question>
<div class="container">
    <div class="col-md-15">
        <h2 class="mb-4">Questions</h2>
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Question</th>
                    <th>Answers</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var question in Model)
                {
                    <tr>
                        <td>@question.Id</td>
                        <td style="width: 50%;">
                            <p>@question.QuestionText</p>
                            <form asp-controller="Questions" asp-action="DeleteQuestion" method="post">
                                <input type="hidden" name="id" value="@question.Id" />
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </td>
                        <td style="width: 50%;">
                            @foreach (var answer in question.Answers)
                            {
                                <p>@answer.Id - @answer.AnswerText - @answer.IsCorrect</p>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

QuizApp-main/QuizApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuizApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuizApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuizApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 bg-light" style="height: 100vh">
                <div class="side-menu">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Questions" asp-action="GetQuestions">QUESTIONS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Questions" asp-action="AddQuestion">ADD QUESTION</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - QuizApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>